name: Spawn runner
on:
  workflow_dispatch:

jobs:
  spawn:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Request registration token
        run: |
          response=$(curl -s -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/tithanayut/private_repo/actions/runners/registration-token)
          token=$(jq -r '.token' <<< "${response}")
          echo $token
    
      # - name: Setup runner
      #   run: |
      #     mkdir actions-runner && cd actions-runner
      #     curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
      #     echo "85c1bbd104d539f666a89edef70a18db2596df374a1b51670f2af1578ecbe031  actions-runner-linux-x64-2.312.0.tar.gz" | shasum -a 256 -c
      #     tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz
      #     ./config.sh --url https://github.com/tithanayut/private_repo --token AHJCZ5E6NKW6LGKIIKF6AWDFXMKAQ
      #     ./run.sh
